FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY constants.py .
COPY models.py .
COPY solar_engine.py .
COPY pdf_generator.py .

EXPOSE 8000

CMD ["uvicorn", "main:app_SP", "--host", "0.0.0.0", "--port", "8000"]
 